"""
Tests for US-59-007: Auto-generated caption fallback in _fetch_subtitle().

Verifies that _fetch_subtitle() retries with auto_generated=True when manual
captions are unavailable, respects the allow_auto_generated config flag, and
preserves is_auto_generated metadata in CaptionResult.
"""

import pytest
from pathlib import Path
from unittest.mock import Mock, patch, MagicMock
import tempfile

from src.caption_fetcher import (
    CaptionFetcher,
    CaptionResult,
    CaptionSegment,
    CaptionUnavailableError,
    CaptionFetchError,
    AvailableLanguage,
)
from src.caption.exceptions import CaptionFormatUnavailableError


def _make_caption_result(video_id="dQw4w9WgXcQ", is_auto=False, language="en"):
    """Helper to create a CaptionResult with minimal segments."""
    return CaptionResult(
        video_id=video_id,
        segments=[CaptionSegment(index=0, start_time=0.0, end_time=1.0, text="Hello world")],
        language=language,
        is_auto_generated=is_auto,
        format_source="vtt",
    )


def _make_config(allow_auto_generated=True):
    """Helper to create a mock config with allow_auto_generated setting."""
    config = Mock()
    caption_first = Mock()
    caption_first.allow_auto_generated = allow_auto_generated
    # Also set other fields that CaptionFetcher __init__ reads
    caption_first.timeout = 30
    caption_first.max_retries = 3
    caption_first.retry_delay = 2.0
    caption_first.preferred_formats = ["json3", "vtt", "srt"]
    caption_first.adaptive_format_order = False
    caption_first.pre_check_availability = True
    caption_first.format_timeouts = {}
    config.download.caption_first = caption_first
    return config


@pytest.mark.fast
class TestAutoGeneratedFallback:
    """Tests for auto-generated caption fallback in _fetch_subtitle (US-59-007)."""

    def test_manual_fail_falls_back_to_auto(self):
        """When manual captions fail, _fetch_subtitle retries with auto_generated=True.

        AC: When _fetch_subtitle() fails to find manual captions (auto_generated=False),
        it retries with auto_generated=True before raising CaptionUnavailableError.
        """
        fetcher = CaptionFetcher()
        auto_result = _make_caption_result(is_auto=True)

        # list_available_languages returns English available
        with patch.object(fetcher, 'list_available_languages', return_value=[
            AvailableLanguage(code='en', name='English', is_auto_generated=True),
        ]):
            call_count = 0
            original_auto_values = []

            def mock_format(video_url, video_id, temp_dir, language,
                            auto_generated, fmt, fallback_level=0):
                nonlocal call_count
                call_count += 1
                original_auto_values.append(auto_generated)
                if not auto_generated:
                    raise CaptionUnavailableError(video_id, "no subtitles")
                return auto_result

            with patch.object(fetcher, '_fetch_subtitle_with_format',
                              side_effect=mock_format):
                with tempfile.TemporaryDirectory() as td:
                    result = fetcher._fetch_subtitle(
                        "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
                        "dQw4w9WgXcQ",
                        Path(td),
                        "en",
                        False,  # Start with manual
                    )

                    assert result is not None
                    assert result.is_auto_generated is True
                    # Should have called with False first, then True
                    assert False in original_auto_values
                    assert True in original_auto_values

    def test_auto_fallback_only_on_unavailability(self):
        """Auto fallback only triggers on CaptionUnavailableError, not rate limits.

        AC: The auto-generated fallback only triggers when the error is caption
        unavailability (not rate limits, timeouts, or network errors).
        US-67-002: Now raises CaptionFormatExhaustedError wrapping the last_error.
        """
        from src.caption.exceptions import CaptionFormatExhaustedError

        fetcher = CaptionFetcher()

        with patch.object(fetcher, 'list_available_languages', return_value=[
            AvailableLanguage(code='en', name='English', is_auto_generated=False),
        ]):
            def mock_format(video_url, video_id, temp_dir, language,
                            auto_generated, fmt, fallback_level=0):
                # Simulate a rate limit / network error (not unavailability)
                raise CaptionFetchError(video_id, "rate limit exceeded")

            with patch.object(fetcher, '_fetch_subtitle_with_format',
                              side_effect=mock_format):
                with tempfile.TemporaryDirectory() as td:
                    with pytest.raises(CaptionFormatExhaustedError) as exc_info:
                        fetcher._fetch_subtitle(
                            "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
                            "dQw4w9WgXcQ",
                            Path(td),
                            "en",
                            False,
                        )
                    # Original rate limit error preserved as last_error
                    assert isinstance(exc_info.value.last_error, CaptionFetchError)
                    assert "rate limit" in exc_info.value.last_error.reason

    def test_auto_fallback_respects_config_false(self):
        """Auto fallback is skipped when allow_auto_generated=False.

        AC: Auto-generated fallback respects the existing allow_auto_generated
        config flag (default True) and skips if False.
        """
        config = _make_config(allow_auto_generated=False)
        fetcher = CaptionFetcher(config=config)

        with patch.object(fetcher, 'list_available_languages', return_value=[
            AvailableLanguage(code='en', name='English', is_auto_generated=True),
        ]):
            call_auto_values = []

            def mock_format(video_url, video_id, temp_dir, language,
                            auto_generated, fmt, fallback_level=0):
                call_auto_values.append(auto_generated)
                raise CaptionUnavailableError(video_id, "no subtitles")

            with patch.object(fetcher, '_fetch_subtitle_with_format',
                              side_effect=mock_format):
                with tempfile.TemporaryDirectory() as td:
                    with pytest.raises(CaptionUnavailableError):
                        fetcher._fetch_subtitle(
                            "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
                            "dQw4w9WgXcQ",
                            Path(td),
                            "en",
                            False,
                        )

                    # Should only have tried manual (False), never auto (True)
                    assert all(v is False for v in call_auto_values)

    def test_auto_fallback_respects_config_true(self):
        """Auto fallback triggers when allow_auto_generated=True (default).

        AC: Auto-generated fallback respects the existing allow_auto_generated
        config flag (default True).
        """
        config = _make_config(allow_auto_generated=True)
        fetcher = CaptionFetcher(config=config)
        auto_result = _make_caption_result(is_auto=True)

        with patch.object(fetcher, 'list_available_languages', return_value=[
            AvailableLanguage(code='en', name='English', is_auto_generated=True),
        ]):
            def mock_format(video_url, video_id, temp_dir, language,
                            auto_generated, fmt, fallback_level=0):
                if not auto_generated:
                    raise CaptionUnavailableError(video_id, "no subtitles")
                return auto_result

            with patch.object(fetcher, '_fetch_subtitle_with_format',
                              side_effect=mock_format):
                with tempfile.TemporaryDirectory() as td:
                    result = fetcher._fetch_subtitle(
                        "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
                        "dQw4w9WgXcQ",
                        Path(td),
                        "en",
                        False,
                    )
                    assert result is not None
                    assert result.is_auto_generated is True

    def test_auto_fallback_preserves_is_auto_generated(self):
        """CaptionResult.is_auto_generated=True when auto fallback is used.

        AC: CaptionResult.is_auto_generated is set to True when auto-generated
        fallback is used, preserving quality metadata.
        """
        fetcher = CaptionFetcher()

        with patch.object(fetcher, 'list_available_languages', return_value=[
            AvailableLanguage(code='en', name='English', is_auto_generated=True),
        ]):
            def mock_format(video_url, video_id, temp_dir, language,
                            auto_generated, fmt, fallback_level=0):
                if not auto_generated:
                    raise CaptionUnavailableError(video_id, "no subtitles")
                return _make_caption_result(is_auto=True)

            with patch.object(fetcher, '_fetch_subtitle_with_format',
                              side_effect=mock_format):
                with tempfile.TemporaryDirectory() as td:
                    result = fetcher._fetch_subtitle(
                        "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
                        "dQw4w9WgXcQ",
                        Path(td),
                        "en",
                        False,
                    )

                    assert result.is_auto_generated is True

    def test_auto_only_video_returns_auto_result(self):
        """Video with only auto-generated captions returns result with is_auto_generated=True.

        AC: Unit test verifies that a video with only auto-generated captions returns
        a CaptionResult with is_auto_generated=True after manual caption attempt fails.
        """
        fetcher = CaptionFetcher()

        with patch.object(fetcher, 'list_available_languages', return_value=[
            AvailableLanguage(code='en', name='English (auto-generated)', is_auto_generated=True),
        ]):
            def mock_format(video_url, video_id, temp_dir, language,
                            auto_generated, fmt, fallback_level=0):
                if not auto_generated:
                    # Manual captions don't exist
                    raise CaptionUnavailableError(video_id, "no subtitles")
                # Auto-generated captions exist
                return CaptionResult(
                    video_id=video_id,
                    segments=[
                        CaptionSegment(index=0, start_time=0.0, end_time=2.0, text="Auto caption text"),
                        CaptionSegment(index=1, start_time=2.0, end_time=4.0, text="More auto text"),
                    ],
                    language="en",
                    is_auto_generated=True,
                    format_source="vtt",
                )

            with patch.object(fetcher, '_fetch_subtitle_with_format',
                              side_effect=mock_format):
                with tempfile.TemporaryDirectory() as td:
                    result = fetcher._fetch_subtitle(
                        "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
                        "dQw4w9WgXcQ",
                        Path(td),
                        "en",
                        False,  # Request manual first
                    )

                    # Verify the result
                    assert result is not None
                    assert result.is_auto_generated is True
                    assert len(result.segments) == 2
                    assert result.segments[0].text == "Auto caption text"

    def test_no_fallback_when_already_auto(self):
        """When called with auto_generated=True already, no redundant retry."""
        fetcher = CaptionFetcher()

        with patch.object(fetcher, 'list_available_languages', return_value=[
            AvailableLanguage(code='en', name='English', is_auto_generated=True),
        ]):
            call_count = 0

            def mock_format(video_url, video_id, temp_dir, language,
                            auto_generated, fmt, fallback_level=0):
                nonlocal call_count
                call_count += 1
                raise CaptionUnavailableError(video_id, "no subtitles")

            with patch.object(fetcher, '_fetch_subtitle_with_format',
                              side_effect=mock_format):
                with tempfile.TemporaryDirectory() as td:
                    with pytest.raises(CaptionUnavailableError):
                        fetcher._fetch_subtitle(
                            "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
                            "dQw4w9WgXcQ",
                            Path(td),
                            "en",
                            True,  # Already requesting auto
                        )

                    # Should only try formats once (no fallback loop)
                    # 1 call per format (3 formats) = 3 max, but CaptionUnavailableError
                    # breaks the loop immediately, so only 1 call
                    assert call_count == 1

    def test_format_unavailable_triggers_auto_fallback(self):
        """CaptionFormatUnavailableError also triggers auto fallback.

        AC: The auto-generated fallback only triggers when the error is caption
        unavailability (not rate limits, timeouts, or network errors).
        CaptionFormatUnavailableError IS a form of unavailability.
        """
        fetcher = CaptionFetcher()
        auto_result = _make_caption_result(is_auto=True)

        with patch.object(fetcher, 'list_available_languages', return_value=[
            AvailableLanguage(code='en', name='English', is_auto_generated=True),
        ]):
            call_auto_values = []

            def mock_format(video_url, video_id, temp_dir, language,
                            auto_generated, fmt, fallback_level=0):
                call_auto_values.append(auto_generated)
                if not auto_generated:
                    raise CaptionFormatUnavailableError(
                        video_id, fmt, "format not available"
                    )
                return auto_result

            with patch.object(fetcher, '_fetch_subtitle_with_format',
                              side_effect=mock_format):
                with tempfile.TemporaryDirectory() as td:
                    result = fetcher._fetch_subtitle(
                        "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
                        "dQw4w9WgXcQ",
                        Path(td),
                        "en",
                        False,
                    )

                    assert result is not None
                    assert result.is_auto_generated is True

    def test_default_config_allows_auto(self):
        """Default config (no config) allows auto-generated fallback."""
        fetcher = CaptionFetcher()
        assert fetcher._is_auto_fallback_allowed() is True

    def test_config_allow_auto_true(self):
        """Config with allow_auto_generated=True allows fallback."""
        config = _make_config(allow_auto_generated=True)
        fetcher = CaptionFetcher(config=config)
        assert fetcher._is_auto_fallback_allowed() is True

    def test_config_allow_auto_false(self):
        """Config with allow_auto_generated=False disallows fallback."""
        config = _make_config(allow_auto_generated=False)
        fetcher = CaptionFetcher(config=config)
        assert fetcher._is_auto_fallback_allowed() is False


@pytest.mark.fast
class TestAutoFallbackMetrics:
    """Tests for auto-generated fallback metrics tracking (US-62-005)."""

    def test_auto_fallback_records_metrics(self):
        """Auto fallback records auto_fallback_count in metrics.

        AC US-62-005: Metrics track count of videos using auto-generated vs manual captions.
        When auto-generated fallback is used, auto_fallback_count should be incremented.
        """
        from src.caption.metrics import CaptionMetrics

        fetcher = CaptionFetcher()
        auto_result = _make_caption_result(is_auto=True)
        metrics = CaptionMetrics()

        # Set the metrics reference on the fetcher
        fetcher._active_metrics = metrics

        with patch.object(fetcher, 'list_available_languages', return_value=[
            AvailableLanguage(code='en', name='English', is_auto_generated=True),
        ]):
            def mock_format(video_url, video_id, temp_dir, language,
                            auto_generated, fmt, fallback_level=0):
                if not auto_generated:
                    raise CaptionUnavailableError(video_id, "no subtitles")
                return auto_result

            with patch.object(fetcher, '_fetch_subtitle_with_format',
                              side_effect=mock_format):
                with tempfile.TemporaryDirectory() as td:
                    result = fetcher._fetch_subtitle(
                        "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
                        "dQw4w9WgXcQ",
                        Path(td),
                        "en",
                        False,
                    )

                    # Verify result is auto-generated
                    assert result is not None
                    assert result.is_auto_generated is True

                    # Verify metrics were recorded
                    assert metrics.auto_fallback_count == 1

    def test_auto_fallback_logs_selection_reason(self):
        """Auto fallback logs 'auto-generated fallback' as selection reason in metrics.

        AC US-62-005: Selection reason logged as 'auto-generated fallback' in metrics.
        """
        from src.caption.metrics import CaptionMetrics

        fetcher = CaptionFetcher()
        auto_result = _make_caption_result(is_auto=True)
        metrics = CaptionMetrics()

        # Set the metrics reference on the fetcher
        fetcher._active_metrics = metrics

        with patch.object(fetcher, 'list_available_languages', return_value=[
            AvailableLanguage(code='en', name='English', is_auto_generated=True),
        ]):
            def mock_format(video_url, video_id, temp_dir, language,
                            auto_generated, fmt, fallback_level=0):
                if not auto_generated:
                    raise CaptionUnavailableError(video_id, "no subtitles")
                return auto_result

            with patch.object(fetcher, '_fetch_subtitle_with_format',
                              side_effect=mock_format):
                with tempfile.TemporaryDirectory() as td:
                    fetcher._fetch_subtitle(
                        "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
                        "dQw4w9WgXcQ",
                        Path(td),
                        "en",
                        False,
                    )

                    # Verify language_selection_trace has the fallback entry
                    assert len(metrics.language_selection_trace) == 1
                    trace = metrics.language_selection_trace[0]
                    assert trace['video_id'] == 'dQw4w9WgXcQ'
                    assert trace['selection_reason'] == 'auto-generated fallback'
                    assert trace['is_auto_generated'] is True

    def test_no_metrics_when_manual_succeeds(self):
        """No auto_fallback_count when manual captions succeed.

        AC US-62-005: Metrics should distinguish between videos that used
        manual captions (no fallback) vs auto-generated fallback.
        """
        from src.caption.metrics import CaptionMetrics

        fetcher = CaptionFetcher()
        manual_result = _make_caption_result(is_auto=False)  # Manual captions
        metrics = CaptionMetrics()

        # Set the metrics reference on the fetcher
        fetcher._active_metrics = metrics

        with patch.object(fetcher, 'list_available_languages', return_value=[
            AvailableLanguage(code='en', name='English', is_auto_generated=False),
        ]):
            def mock_format(video_url, video_id, temp_dir, language,
                            auto_generated, fmt, fallback_level=0):
                return manual_result  # Manual succeeds

            with patch.object(fetcher, '_fetch_subtitle_with_format',
                              side_effect=mock_format):
                with tempfile.TemporaryDirectory() as td:
                    result = fetcher._fetch_subtitle(
                        "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
                        "dQw4w9WgXcQ",
                        Path(td),
                        "en",
                        False,
                    )

                    # Verify result is manual
                    assert result is not None
                    assert result.is_auto_generated is False

                    # Verify no auto_fallback recorded
                    assert metrics.auto_fallback_count == 0
                    # No language selection trace for fallback
                    assert len(metrics.language_selection_trace) == 0

    def test_auto_fallback_not_recorded_when_config_false(self):
        """Auto fallback not recorded when allow_auto_generated=False.

        AC US-62-005: Test verifies auto-generated fallback disabled when config is false.
        """
        from src.caption.metrics import CaptionMetrics

        config = _make_config(allow_auto_generated=False)
        fetcher = CaptionFetcher(config=config)
        metrics = CaptionMetrics()

        # Set the metrics reference on the fetcher
        fetcher._active_metrics = metrics

        with patch.object(fetcher, 'list_available_languages', return_value=[
            AvailableLanguage(code='en', name='English', is_auto_generated=True),
        ]):
            def mock_format(video_url, video_id, temp_dir, language,
                            auto_generated, fmt, fallback_level=0):
                raise CaptionUnavailableError(video_id, "no subtitles")

            with patch.object(fetcher, '_fetch_subtitle_with_format',
                              side_effect=mock_format):
                with tempfile.TemporaryDirectory() as td:
                    with pytest.raises(CaptionUnavailableError):
                        fetcher._fetch_subtitle(
                            "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
                            "dQw4w9WgXcQ",
                            Path(td),
                            "en",
                            False,
                        )

                    # Verify no auto_fallback recorded (fallback was disabled)
                    assert metrics.auto_fallback_count == 0


@pytest.mark.fast
class TestAutoSubCacheKeySuffix:
    """Tests for US-67-012: Auto-generated captions use '_autosub' cache key suffix."""

    def test_manual_caption_cache_key_no_suffix(self):
        """Manual captions use standard cache key without '_autosub' suffix.

        AC: Auto-generated captions are cached with a distinct cache key suffix
        '_autosub' to avoid confusion with manual captions.
        """
        from src.caption.cache import CaptionCache
        cache = CaptionCache()
        key = cache._make_cache_key("dQw4w9WgXcQ", "en", is_auto_generated=False)
        assert key == "dQw4w9WgXcQ_en"
        assert "_autosub" not in key

    def test_auto_generated_caption_cache_key_has_autosub_suffix(self):
        """Auto-generated captions use '_autosub' suffix in cache key.

        AC: Auto-generated captions are cached with a distinct cache key suffix
        '_autosub' to avoid confusion with manual captions.
        """
        from src.caption.cache import CaptionCache
        cache = CaptionCache()
        key = cache._make_cache_key("dQw4w9WgXcQ", "en", is_auto_generated=True)
        assert key == "dQw4w9WgXcQ_en_autosub"

    def test_store_auto_generated_uses_autosub_key(self):
        """Storing auto-generated caption result uses '_autosub' key.

        AC: Auto-generated captions are cached with a distinct cache key suffix
        '_autosub' to avoid confusion with manual captions.
        """
        from src.caption.cache import CaptionCache
        cache = CaptionCache()

        auto_result = CaptionResult(
            video_id="dQw4w9WgXcQ",
            segments=[CaptionSegment(index=0, start_time=0.0, end_time=1.0, text="Hello")],
            language="en",
            is_auto_generated=True,
            format_source="vtt",
        )

        with patch.object(cache, 'set') as mock_set:
            cache.store(auto_result)
            # Verify the key passed to set() has '_autosub' suffix
            call_args = mock_set.call_args
            assert call_args is not None
            stored_key = call_args[0][0]
            assert stored_key == "dQw4w9WgXcQ_en_autosub"

    def test_store_manual_caption_uses_standard_key(self):
        """Storing manual caption result uses standard key without suffix.

        AC: Auto-generated captions are cached with a distinct cache key suffix
        '_autosub' to avoid confusion with manual captions.
        """
        from src.caption.cache import CaptionCache
        cache = CaptionCache()

        manual_result = CaptionResult(
            video_id="dQw4w9WgXcQ",
            segments=[CaptionSegment(index=0, start_time=0.0, end_time=1.0, text="Hello")],
            language="en",
            is_auto_generated=False,
            format_source="vtt",
        )

        with patch.object(cache, 'set') as mock_set:
            cache.store(manual_result)
            call_args = mock_set.call_args
            assert call_args is not None
            stored_key = call_args[0][0]
            assert stored_key == "dQw4w9WgXcQ_en"
            assert "_autosub" not in stored_key

    def test_get_caption_with_auto_generated_true_uses_autosub_key(self):
        """Looking up with auto_generated=True uses '_autosub' key.

        AC: Auto-generated captions are cached with a distinct cache key suffix
        '_autosub' to avoid confusion with manual captions.
        """
        from src.caption.cache import CaptionCache
        cache = CaptionCache()

        with patch.object(cache, 'get', return_value=None) as mock_get:
            cache.get_caption("dQw4w9WgXcQ", "en", auto_generated=True)
            mock_get.assert_called_once_with("dQw4w9WgXcQ_en_autosub")

    def test_get_caption_default_tries_both_keys(self):
        """Default get_caption (auto_generated=None) tries manual then auto key.

        AC: Auto-generated captions are cached with a distinct cache key suffix
        '_autosub' to avoid confusion with manual captions.
        """
        from src.caption.cache import CaptionCache
        cache = CaptionCache()

        with patch.object(cache, 'get', return_value=None) as mock_get:
            cache.get_caption("dQw4w9WgXcQ", "en")
            # Should try manual key first, then auto key
            assert mock_get.call_count == 2
            calls = [c[0][0] for c in mock_get.call_args_list]
            assert calls[0] == "dQw4w9WgXcQ_en"
            assert calls[1] == "dQw4w9WgXcQ_en_autosub"
