"""
Tests for US-85-004: Auto-generate _STATE_ATTR_DEFAULTS from PipelineState annotations.

Verifies that _STATE_ATTR_DEFAULTS is auto-derived from dataclasses.fields(PipelineState)
and that adding new fields to PipelineState automatically populates the defaults dict.
"""

import dataclasses
from unittest.mock import patch

import pytest

from src.stages import _STATE_ATTR_DEFAULTS, _build_state_attr_defaults
from src.state import PipelineState


class TestAutoGeneratedDefaults:
    """Verify _STATE_ATTR_DEFAULTS is auto-generated from PipelineState."""

    @pytest.mark.fast
    def test_every_defaulted_field_present(self):
        """_STATE_ATTR_DEFAULTS contains an entry for every PipelineState field with a default."""
        for f in dataclasses.fields(PipelineState):
            has_default = (
                f.default is not dataclasses.MISSING
                or f.default_factory is not dataclasses.MISSING
            )
            if has_default:
                assert f.name in _STATE_ATTR_DEFAULTS, (
                    f"PipelineState field '{f.name}' has a default but is missing "
                    f"from _STATE_ATTR_DEFAULTS — auto-generation may be broken"
                )

    @pytest.mark.fast
    def test_values_match_dataclass_defaults(self):
        """Auto-generated values match calling default/default_factory on PipelineState."""
        for f in dataclasses.fields(PipelineState):
            if f.default is not dataclasses.MISSING:
                assert _STATE_ATTR_DEFAULTS[f.name] == f.default
            elif f.default_factory is not dataclasses.MISSING:
                expected = f.default_factory()
                assert _STATE_ATTR_DEFAULTS[f.name] == expected, (
                    f"_STATE_ATTR_DEFAULTS['{f.name}'] = {_STATE_ATTR_DEFAULTS[f.name]!r} "
                    f"but default_factory() = {expected!r}"
                )

    @pytest.mark.fast
    def test_no_extra_keys_beyond_pipeline_state(self):
        """_STATE_ATTR_DEFAULTS should not contain keys absent from PipelineState."""
        field_names = {f.name for f in dataclasses.fields(PipelineState)}
        extra = set(_STATE_ATTR_DEFAULTS.keys()) - field_names
        assert not extra, f"Extra keys in _STATE_ATTR_DEFAULTS: {extra}"

    @pytest.mark.fast
    def test_build_function_is_deterministic(self):
        """Calling _build_state_attr_defaults() twice yields identical dicts."""
        d1 = _build_state_attr_defaults()
        d2 = _build_state_attr_defaults()
        assert d1 == d2

    @pytest.mark.fast
    def test_new_field_automatically_appears(self):
        """Adding a new field to PipelineState automatically appears in defaults dict.

        Simulates adding a hypothetical 'test_new_field' to PipelineState and verifies
        _build_state_attr_defaults() picks it up without manual edits.
        """
        # Create a mock field that simulates a new PipelineState field
        mock_field = dataclasses.field(default_factory=list)
        mock_field.name = 'hypothetical_new_field'
        # Initialize the internal field metadata that dataclasses sets
        mock_field._field_type = dataclasses._FIELD

        original_fields = dataclasses.fields(PipelineState)
        extended_fields = tuple(original_fields) + (mock_field,)

        with patch('dataclasses.fields', return_value=extended_fields):
            result = _build_state_attr_defaults()

        assert 'hypothetical_new_field' in result, (
            "A new PipelineState field with a default should auto-appear in defaults dict"
        )
        assert result['hypothetical_new_field'] == [], (
            "New list field should default to []"
        )
