"""
Caption quality assessment functions.

Provides functions for determining caption quality and calculating
segment quality metrics.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, List, Optional

from .models import SegmentQualityMetrics

if TYPE_CHECKING:
    from .models import CaptionSegment


def determine_caption_quality(
    is_auto_generated: bool,
    segment_count: int,
    total_duration: float,
    min_segments_for_high: int = 10,
    max_avg_duration_for_high: float = 10.0,
) -> str:
    """Determine caption quality based on source and completeness.

    Quality levels (US-007):
    - 'high': Human-uploaded captions with good completeness
    - 'medium': Auto-generated captions OR sparse human captions
    - 'low': Very sparse/incomplete captions or missing

    Assessment criteria:
    1. Source type: Human captions start at 'high', auto at 'medium'
    2. Completeness: Need at least min_segments_for_high segments for 'high'
    3. Density: Average segment duration > max_avg_duration indicates sparse captions

    Args:
        is_auto_generated: Whether captions are auto-generated by YouTube
        segment_count: Number of caption segments
        total_duration: Total caption duration in seconds
        min_segments_for_high: Minimum segments required for 'high' quality
        max_avg_duration_for_high: Max average segment duration for 'high' quality

    Returns:
        'high', 'medium', or 'low'

    Examples:
        >>> determine_caption_quality(False, 100, 300.0)  # Human, dense
        'high'
        >>> determine_caption_quality(True, 100, 300.0)   # Auto, dense
        'medium'
        >>> determine_caption_quality(False, 5, 300.0)    # Human, sparse
        'medium'
        >>> determine_caption_quality(True, 2, 60.0)      # Auto, very sparse
        'low'
    """
    # No segments = low quality (fallback/missing)
    if segment_count == 0:
        return 'low'

    # Calculate average segment duration
    avg_duration = total_duration / segment_count if segment_count > 0 else float('inf')

    # Very sparse captions (few segments or very long avg duration) = low quality
    if segment_count < 3 or (total_duration > 60 and avg_duration > 30.0):
        return 'low'

    # Auto-generated captions cap at 'medium'
    if is_auto_generated:
        # Even auto-generated needs reasonable completeness
        if segment_count >= min_segments_for_high and avg_duration <= max_avg_duration_for_high:
            return 'medium'
        return 'medium' if avg_duration <= 20.0 else 'low'

    # Human-uploaded captions
    # Need good completeness for 'high'
    if segment_count >= min_segments_for_high and avg_duration <= max_avg_duration_for_high:
        return 'high'

    # Sparse human captions = medium
    return 'medium'


def calculate_segment_metrics(
    segments: List['CaptionSegment'],
    total_duration: Optional[float] = None,
) -> SegmentQualityMetrics:
    """Calculate sophisticated quality metrics for caption segments (US-006 Sprint 8).

    Analyzes segments to produce quality scores based on:
    1. density_score: Segments per minute, normalized to 0-1 scale
       - Optimal: 10-15 segments/minute (typical human captions)
       - Too low (<5/min): Sparse captions, may miss content
       - Too high (>25/min): Possibly auto-generated with micro-segments
    2. timing_precision: Percentage with exact millisecond timestamps
       - Human captions often use round numbers (1.0, 2.5, etc.)
       - Auto-captions have precise timestamps (1.234, 2.891, etc.)
       - Lower precision often indicates human-curated captions
    3. text_completeness: Average characters per segment vs expected (50-200)
       - Very short (<50 chars avg): Truncated or single-word segments
       - Optimal (50-200): Full sentences/phrases
       - Very long (>200 chars avg): May indicate missed segment breaks

    The combined quality_score uses weights: 0.4*density + 0.3*precision + 0.3*completeness.

    Args:
        segments: List of CaptionSegment objects to analyze.
        total_duration: Total video duration in seconds. If not provided,
            uses the span from first to last segment.

    Returns:
        SegmentQualityMetrics with all scores and the combined quality_score.
    """
    if not segments:
        return SegmentQualityMetrics(
            density_score=0.0,
            timing_precision=0.0,
            text_completeness=0.0,
            quality_score=0.0,
            segment_count=0,
            total_duration=0.0,
        )

    # Calculate total duration if not provided
    if total_duration is None or total_duration <= 0:
        if len(segments) > 0:
            total_duration = segments[-1].end_time - segments[0].start_time
        else:
            total_duration = 0.0

    # Avoid division by zero
    if total_duration <= 0:
        total_duration = 1.0  # Assume 1 second minimum

    segment_count = len(segments)

    # 1. Density score: segments per minute, normalized to 0-1
    # Optimal is ~10-15 segments/minute
    duration_minutes = total_duration / 60.0
    if duration_minutes > 0:
        segments_per_minute = segment_count / duration_minutes
    else:
        segments_per_minute = 0.0

    # Normalize: 0 at 0/min, 1.0 at 10-15/min, drops for very high values
    # Use a bell curve centered around 12 segments/min
    optimal_density = 12.0
    density_deviation = abs(segments_per_minute - optimal_density) / optimal_density
    density_score = max(0.0, 1.0 - density_deviation * 0.5)
    density_score = min(1.0, density_score)

    # 2. Timing precision: percentage with exact millisecond timestamps
    # Check if timestamps have sub-second precision (auto-generated pattern)
    precise_count = 0
    for seg in segments:
        start_ms = (seg.start_time * 1000) % 1000
        end_ms = (seg.end_time * 1000) % 1000
        # Precise if not at round 100ms intervals
        if start_ms % 100 != 0 or end_ms % 100 != 0:
            precise_count += 1

    timing_precision = precise_count / segment_count if segment_count > 0 else 0.0

    # For quality scoring, lower precision (round numbers) is often better
    # because it indicates human curation. Invert the score.
    # But we still want SOME precision, so we use a U-shaped curve
    # Best at ~0.3-0.5 precision (some rounding but not all identical)
    precision_quality = 1.0 - abs(timing_precision - 0.4) * 1.5
    precision_quality = max(0.0, min(1.0, precision_quality))

    # 3. Text completeness: average chars per segment vs expected (50-200)
    if segment_count > 0:
        total_chars = sum(len(seg.text) for seg in segments)
        avg_chars = total_chars / segment_count
    else:
        avg_chars = 0.0

    # Optimal range: 50-200 characters per segment
    min_optimal = 50.0
    max_optimal = 200.0

    if avg_chars < min_optimal:
        # Too short: score drops linearly to 0 at 0 chars
        text_completeness = avg_chars / min_optimal
    elif avg_chars > max_optimal:
        # Too long: score drops linearly, but not as harshly
        # 400 chars would give 0.5, 600 chars would give 0.0
        overage = (avg_chars - max_optimal) / (max_optimal * 2)
        text_completeness = max(0.0, 1.0 - overage)
    else:
        # In optimal range: full score
        text_completeness = 1.0

    # Combine scores with weights: 0.4*density + 0.3*precision + 0.3*completeness
    quality_score = (
        0.4 * density_score +
        0.3 * precision_quality +
        0.3 * text_completeness
    )
    quality_score = max(0.0, min(1.0, quality_score))

    return SegmentQualityMetrics(
        density_score=density_score,
        timing_precision=timing_precision,
        text_completeness=text_completeness,
        quality_score=quality_score,
        segment_count=segment_count,
        total_duration=total_duration,
    )
