"""
YouTube caption fetcher module.

Fetches captions/subtitles from YouTube videos using yt-dlp.
This is the foundation for caption-first mode, enabling transcript retrieval
without downloading video content.

Usage:
    fetcher = CaptionFetcher()
    result = fetcher.fetch_captions("dQw4w9WgXcQ")
    for segment in result.segments:
        print(f"{segment.start_time:.2f} -> {segment.end_time:.2f}: {segment.text}")

    # With caching:
    cache = CaptionCache(config.download.caption_first)
    cached = cache.get("dQw4w9WgXcQ", "en")
    if cached:
        print(f"Cache hit: {len(cached.segments)} segments")
    else:
        result = fetcher.fetch_captions("dQw4w9WgXcQ")
        cache.store(result)
"""

from __future__ import annotations

import json
import logging
import os
import re
import subprocess
import tempfile
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING, Any, Dict, List, Optional

from .cache import BaseCache, CacheEntry

if TYPE_CHECKING:
    from .config import Config
    from .config.sections.download import CaptionFirstConfig

logger = logging.getLogger(__name__)


def determine_caption_quality(
    is_auto_generated: bool,
    segment_count: int,
    total_duration: float,
    min_segments_for_high: int = 10,
    max_avg_duration_for_high: float = 10.0,
) -> str:
    """Determine caption quality based on source and completeness.

    Quality levels (US-007):
    - 'high': Human-uploaded captions with good completeness
    - 'medium': Auto-generated captions OR sparse human captions
    - 'low': Very sparse/incomplete captions or missing

    Assessment criteria:
    1. Source type: Human captions start at 'high', auto at 'medium'
    2. Completeness: Need at least min_segments_for_high segments for 'high'
    3. Density: Average segment duration > max_avg_duration indicates sparse captions

    Args:
        is_auto_generated: Whether captions are auto-generated by YouTube
        segment_count: Number of caption segments
        total_duration: Total caption duration in seconds
        min_segments_for_high: Minimum segments required for 'high' quality
        max_avg_duration_for_high: Max average segment duration for 'high' quality

    Returns:
        'high', 'medium', or 'low'

    Examples:
        >>> determine_caption_quality(False, 100, 300.0)  # Human, dense
        'high'
        >>> determine_caption_quality(True, 100, 300.0)   # Auto, dense
        'medium'
        >>> determine_caption_quality(False, 5, 300.0)    # Human, sparse
        'medium'
        >>> determine_caption_quality(True, 2, 60.0)      # Auto, very sparse
        'low'
    """
    # No segments = low quality (fallback/missing)
    if segment_count == 0:
        return 'low'

    # Calculate average segment duration
    avg_duration = total_duration / segment_count if segment_count > 0 else float('inf')

    # Very sparse captions (few segments or very long avg duration) = low quality
    if segment_count < 3 or (total_duration > 60 and avg_duration > 30.0):
        return 'low'

    # Auto-generated captions cap at 'medium'
    if is_auto_generated:
        # Even auto-generated needs reasonable completeness
        if segment_count >= min_segments_for_high and avg_duration <= max_avg_duration_for_high:
            return 'medium'
        return 'medium' if avg_duration <= 20.0 else 'low'

    # Human-uploaded captions
    # Need good completeness for 'high'
    if segment_count >= min_segments_for_high and avg_duration <= max_avg_duration_for_high:
        return 'high'

    # Sparse human captions = medium
    return 'medium'


class CaptionError(Exception):
    """Base exception for caption-related errors."""
    pass


class CaptionUnavailableError(CaptionError):
    """Raised when captions are not available for a video.

    This indicates the video genuinely has no captions (auto or manual),
    as opposed to a temporary fetch failure.
    """
    def __init__(self, video_id: str, reason: str = ""):
        self.video_id = video_id
        self.reason = reason
        message = f"No captions available for video {video_id}"
        if reason:
            message += f": {reason}"
        super().__init__(message)


class CaptionFetchError(CaptionError):
    """Raised when caption fetch fails due to a temporary/network error.

    This indicates a potentially retryable failure, not that captions
    don't exist.
    """
    def __init__(self, video_id: str, reason: str = ""):
        self.video_id = video_id
        self.reason = reason
        message = f"Failed to fetch captions for video {video_id}"
        if reason:
            message += f": {reason}"
        super().__init__(message)


@dataclass
class CaptionSegment:
    """A single caption segment with timing information.

    Compatible with TranscriptSegment for downstream matching.
    """
    index: int
    start_time: float
    end_time: float
    text: str
    source_file: str = ""  # Video ID or path

    def to_dict(self) -> dict:
        """Convert to dictionary for serialization."""
        return {
            'index': self.index,
            'start': self.start_time,
            'end': self.end_time,
            'text': self.text,
            'source_file': self.source_file,
        }


@dataclass
class CaptionResult:
    """Result of a caption fetch operation."""
    video_id: str
    segments: List[CaptionSegment] = field(default_factory=list)
    language: str = ""  # ISO 639-1 code (e.g., 'en')
    is_auto_generated: bool = False
    format_source: str = ""  # 'vtt', 'srv3', 'json3', etc.

    @property
    def text(self) -> str:
        """Get full caption text concatenated."""
        return " ".join(seg.text for seg in self.segments)

    @property
    def duration(self) -> float:
        """Get total duration covered by captions."""
        if not self.segments:
            return 0.0
        return self.segments[-1].end_time - self.segments[0].start_time

    @property
    def caption_quality(self) -> str:
        """Determine caption quality based on source and completeness.

        Quality levels:
        - 'high': Human-uploaded captions (is_auto_generated=False) with good completeness
        - 'medium': Auto-generated captions with reasonable completeness
        - 'low': Missing, sparse, or fallback captions

        Quality is assessed based on:
        1. is_auto_generated flag (human > auto)
        2. Segment count (completeness indicator)
        3. Average segment duration (too long = sparse captions)

        Returns:
            'high', 'medium', or 'low'
        """
        return determine_caption_quality(
            is_auto_generated=self.is_auto_generated,
            segment_count=len(self.segments),
            total_duration=self.duration
        )

    def to_dict(self) -> dict:
        """Convert to dictionary for serialization."""
        return {
            'video_id': self.video_id,
            'segments': [seg.to_dict() for seg in self.segments],
            'language': self.language,
            'is_auto_generated': self.is_auto_generated,
            'format_source': self.format_source,
            'caption_quality': self.caption_quality,
        }


@dataclass
class AvailableLanguage:
    """Represents an available caption language for a video."""
    code: str  # ISO 639-1 code (e.g., 'en', 'es', 'fr')
    name: str  # Human-readable name (e.g., 'English', 'Spanish')
    is_auto_generated: bool  # True if auto-generated captions


class CaptionFetcher:
    """Fetches YouTube captions using yt-dlp.

    Supports multiple caption formats (VTT, SRT, JSON3) and auto-converts
    them to a common segment format.

    Retry behavior (US-008):
    - Network errors (CaptionFetchError) are retried with exponential backoff
    - Permanent errors (CaptionUnavailableError) are NOT retried
    - After max_retries, video is marked for transcription fallback
    - Detailed logging includes video_id, error type, and retry attempt

    Example:
        fetcher = CaptionFetcher()
        result = fetcher.fetch_captions("dQw4w9WgXcQ")
        print(f"Found {len(result.segments)} segments, auto={result.is_auto_generated}")

        # List available languages first
        languages = fetcher.list_available_languages("dQw4w9WgXcQ")
        for lang in languages:
            print(f"{lang.code}: {lang.name} (auto={lang.is_auto_generated})")

        # With retry (US-008):
        try:
            result = fetcher.fetch_captions_with_retry("dQw4w9WgXcQ")
        except CaptionFetchError as e:
            # Mark for transcription fallback
            print(f"Caption fetch failed after retries: {e}")
    """

    def __init__(self, config: Optional['Config'] = None):
        """Initialize the caption fetcher.

        Args:
            config: Optional config for cookies and other settings.
        """
        self.config = config
        self._timeout = 60  # seconds

        # Retry settings from config (US-008)
        self._max_retries = 3
        self._retry_delay = 2.0
        if config:
            try:
                caption_first = getattr(config.download, 'caption_first', None)
                if caption_first:
                    self._max_retries = getattr(caption_first, 'max_retries', 3)
                    self._retry_delay = getattr(caption_first, 'retry_delay', 2.0)
                    # Also use caption_first timeout if configured
                    timeout = getattr(caption_first, 'timeout', None)
                    if timeout:
                        self._timeout = timeout
            except AttributeError:
                pass

    def list_available_languages(self, video_id: str) -> List[AvailableLanguage]:
        """List available caption languages for a YouTube video.

        Uses yt-dlp to query subtitle metadata without downloading.
        Returns both manual and auto-generated caption languages.

        Args:
            video_id: YouTube video ID (11 characters).

        Returns:
            List of AvailableLanguage objects, sorted with manual captions first,
            then auto-generated. Within each group, sorted by language code.

        Raises:
            CaptionFetchError: If unable to query video metadata.

        Example:
            languages = fetcher.list_available_languages("dQw4w9WgXcQ")
            # [AvailableLanguage(code='en', name='English', is_auto_generated=False),
            #  AvailableLanguage(code='en', name='English (auto-generated)', is_auto_generated=True)]
        """
        if not self._is_valid_video_id(video_id):
            raise CaptionFetchError(video_id, f"Invalid video ID format: {video_id}")

        video_url = f"https://www.youtube.com/watch?v={video_id}"

        cmd = [
            'yt-dlp',
            video_url,
            '--skip-download',
            '--list-subs',
            '--no-playlist',
            '--no-warnings',
        ]

        # Add cookies if configured
        cmd.extend(self._get_cookies_args())

        try:
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=self._timeout
            )

            # Parse the output to extract available languages
            return self._parse_list_subs_output(result.stdout, result.stderr)

        except subprocess.TimeoutExpired:
            raise CaptionFetchError(video_id, f"Timeout after {self._timeout}s")
        except Exception as e:
            raise CaptionFetchError(video_id, str(e))

    def _parse_list_subs_output(
        self,
        stdout: str,
        stderr: str
    ) -> List[AvailableLanguage]:
        """Parse yt-dlp --list-subs output to extract available languages.

        The output format looks like:
            [info] Available subtitles for VIDEO_ID:
            Language  Name                 Formats
            en        English              vtt, ttml, srv3, srv2, srv1, json3
            es        Spanish              vtt, ttml, srv3, srv2, srv1, json3

            [info] Available automatic captions for VIDEO_ID:
            Language  Name                              Formats
            en        English (auto-generated)          vtt, ttml, srv3, srv2, srv1, json3

        Args:
            stdout: Standard output from yt-dlp.
            stderr: Standard error from yt-dlp.

        Returns:
            List of AvailableLanguage objects.
        """
        languages = []
        combined_output = stdout + "\n" + stderr

        # Track which section we're in
        in_manual_section = False
        in_auto_section = False

        # Pattern to match language lines (after header)
        # Format: "en        English              vtt, ttml, ..."
        lang_line_pattern = re.compile(
            r'^([a-z]{2,3}(?:-[A-Za-z]{2,4})?)\s+(.+?)\s+(?:vtt|ttml|srv|json)',
            re.IGNORECASE
        )

        for line in combined_output.split('\n'):
            line = line.strip()

            # Detect section headers
            if 'Available subtitles' in line:
                in_manual_section = True
                in_auto_section = False
                continue
            elif 'Available automatic captions' in line:
                in_manual_section = False
                in_auto_section = True
                continue
            elif line.startswith('[info]') or line.startswith('Language'):
                # Skip info lines and headers
                continue
            elif not line:
                # Empty line might end a section
                continue

            # Try to parse language line
            match = lang_line_pattern.match(line)
            if match:
                lang_code = match.group(1).lower()
                lang_name = match.group(2).strip()

                # Determine if auto-generated
                is_auto = in_auto_section or '(auto' in lang_name.lower()

                # Clean up the name
                if '(auto-generated)' in lang_name:
                    display_name = lang_name
                elif is_auto:
                    display_name = f"{lang_name} (auto-generated)"
                else:
                    display_name = lang_name

                languages.append(AvailableLanguage(
                    code=lang_code,
                    name=display_name,
                    is_auto_generated=is_auto
                ))

        # Sort: manual captions first, then auto-generated, alphabetically within each
        languages.sort(key=lambda x: (x.is_auto_generated, x.code))

        logger.debug(f"Found {len(languages)} available caption languages")
        return languages

    def select_best_language(
        self,
        available: List[AvailableLanguage],
        preferred: Optional[str] = None,
        fallback_to_english: bool = True,
        prefer_manual: bool = True
    ) -> Optional[AvailableLanguage]:
        """Select the best language from available options using fallback chain.

        Implements the fallback chain:
        1. Preferred language (manual if prefer_manual, else any)
        2. English 'en' (manual if prefer_manual, else any)
        3. Any available language (manual if prefer_manual, else any)

        Args:
            available: List of available languages from list_available_languages().
            preferred: Preferred language code (e.g., 'en', 'es'). If None, uses
                       config.download.caption_first.preferred_language or
                       config.transcription.language.
            fallback_to_english: If True, fall back to English if preferred unavailable.
            prefer_manual: If True, prefer manual captions over auto-generated.

        Returns:
            Selected AvailableLanguage, or None if no languages available.

        Example:
            languages = fetcher.list_available_languages("dQw4w9WgXcQ")
            best = fetcher.select_best_language(languages, preferred='es')
            if best:
                result = fetcher.fetch_captions("dQw4w9WgXcQ", language=best.code)
        """
        if not available:
            logger.warning("No caption languages available to select from")
            return None

        # Determine preferred language from args or config
        if preferred is None:
            preferred = self._get_preferred_language_from_config()

        logger.debug(f"Selecting caption language: preferred={preferred}, "
                    f"fallback_english={fallback_to_english}, prefer_manual={prefer_manual}")

        def find_language(code: str, manual_only: bool = False) -> Optional[AvailableLanguage]:
            """Find a language by code, optionally filtering to manual only."""
            for lang in available:
                if lang.code.lower() == code.lower():
                    if manual_only and lang.is_auto_generated:
                        continue
                    return lang
            return None

        # Step 1: Try preferred language
        if preferred:
            # Try manual first if preferred
            if prefer_manual:
                result = find_language(preferred, manual_only=True)
                if result:
                    logger.info(f"Selected preferred language: {result.code} (manual)")
                    return result

            # Try auto if manual not found
            result = find_language(preferred, manual_only=False)
            if result:
                logger.info(f"Selected preferred language: {result.code} "
                           f"({'auto' if result.is_auto_generated else 'manual'})")
                return result

            logger.debug(f"Preferred language '{preferred}' not available")

        # Step 2: Fall back to English
        if fallback_to_english and (preferred is None or preferred.lower() != 'en'):
            if prefer_manual:
                result = find_language('en', manual_only=True)
                if result:
                    logger.info("Falling back to English (manual)")
                    return result

            result = find_language('en', manual_only=False)
            if result:
                logger.info(f"Falling back to English "
                           f"({'auto' if result.is_auto_generated else 'manual'})")
                return result

            logger.debug("English not available")

        # Step 3: Fall back to any available language
        if prefer_manual:
            manual_langs = [l for l in available if not l.is_auto_generated]
            if manual_langs:
                result = manual_langs[0]  # Already sorted by code
                logger.info(f"Falling back to any available: {result.code} (manual)")
                return result

        if available:
            result = available[0]  # Already sorted: manual first, then auto
            logger.info(f"Falling back to any available: {result.code} "
                       f"({'auto' if result.is_auto_generated else 'manual'})")
            return result

        logger.warning("No suitable caption language found")
        return None

    def _get_preferred_language_from_config(self) -> str:
        """Get preferred language from config.

        Checks in order:
        1. config.download.caption_first.preferred_language
        2. config.transcription.language
        3. Default to 'en'

        Returns:
            Language code (ISO 639-1).
        """
        if not self.config:
            return 'en'

        try:
            # First try caption_first.preferred_language
            caption_first = getattr(self.config.download, 'caption_first', None)
            if caption_first:
                preferred = getattr(caption_first, 'preferred_language', None)
                if preferred:
                    return preferred

            # Then try transcription.language
            transcription = getattr(self.config, 'transcription', None)
            if transcription:
                lang = getattr(transcription, 'language', None)
                if lang:
                    return lang
        except AttributeError:
            pass

        return 'en'

    def fetch_captions_auto_language(
        self,
        video_id: str,
        preferred_language: Optional[str] = None
    ) -> CaptionResult:
        """Fetch captions with automatic language selection.

        Combines list_available_languages and fetch_captions with intelligent
        language selection based on config and availability.

        Args:
            video_id: YouTube video ID.
            preferred_language: Optional override for preferred language.

        Returns:
            CaptionResult with captions in the best available language.

        Raises:
            CaptionUnavailableError: If no captions available in any language.
            CaptionFetchError: If fetch fails due to network/temporary error.
        """
        # List available languages
        available = self.list_available_languages(video_id)

        if not available:
            raise CaptionUnavailableError(
                video_id,
                "No captions available in any language"
            )

        # Select best language
        prefer_manual = True
        if self.config:
            caption_first = getattr(self.config.download, 'caption_first', None)
            if caption_first:
                prefer_manual = getattr(caption_first, 'prefer_human_captions', True)

        selected = self.select_best_language(
            available,
            preferred=preferred_language,
            fallback_to_english=True,
            prefer_manual=prefer_manual
        )

        if not selected:
            raise CaptionUnavailableError(
                video_id,
                "No suitable language found despite available captions"
            )

        # Fetch captions in selected language
        return self.fetch_captions(
            video_id,
            language=selected.code,
            prefer_manual=not selected.is_auto_generated
        )

    def fetch_captions_with_retry(
        self,
        video_id: str,
        language: str = "en",
        prefer_manual: bool = True,
        max_retries: Optional[int] = None,
        retry_delay: Optional[float] = None
    ) -> CaptionResult:
        """Fetch captions with exponential backoff retry logic (US-008).

        Retries on network/temporary errors (CaptionFetchError) but NOT on
        permanent errors (CaptionUnavailableError - when captions don't exist).

        Args:
            video_id: YouTube video ID (11 characters).
            language: Preferred language code (ISO 639-1).
            prefer_manual: If True, prefer manually uploaded captions over auto-generated.
            max_retries: Override max retry attempts (default: config or 3).
            retry_delay: Override base delay between retries (default: config or 2.0s).

        Returns:
            CaptionResult with parsed segments and metadata.

        Raises:
            CaptionUnavailableError: If no captions exist (NOT retried).
            CaptionFetchError: If all retries fail due to network/temporary errors.

        Example:
            try:
                result = fetcher.fetch_captions_with_retry("dQw4w9WgXcQ")
            except CaptionFetchError as e:
                # Mark for transcription fallback after max retries
                needs_transcription.append(video_id)
        """
        retries = max_retries if max_retries is not None else self._max_retries
        delay = retry_delay if retry_delay is not None else self._retry_delay

        return self._with_retry(
            func=lambda: self.fetch_captions(video_id, language, prefer_manual),
            video_id=video_id,
            operation="fetch_captions",
            max_retries=retries,
            retry_delay=delay
        )

    def fetch_captions_auto_language_with_retry(
        self,
        video_id: str,
        preferred_language: Optional[str] = None,
        max_retries: Optional[int] = None,
        retry_delay: Optional[float] = None
    ) -> CaptionResult:
        """Fetch captions with auto language selection and retry logic (US-008).

        Combines automatic language selection with exponential backoff retry.

        Args:
            video_id: YouTube video ID.
            preferred_language: Optional override for preferred language.
            max_retries: Override max retry attempts (default: config or 3).
            retry_delay: Override base delay between retries (default: config or 2.0s).

        Returns:
            CaptionResult with captions in the best available language.

        Raises:
            CaptionUnavailableError: If no captions available in any language (NOT retried).
            CaptionFetchError: If all retries fail due to network/temporary errors.
        """
        retries = max_retries if max_retries is not None else self._max_retries
        delay = retry_delay if retry_delay is not None else self._retry_delay

        return self._with_retry(
            func=lambda: self.fetch_captions_auto_language(video_id, preferred_language),
            video_id=video_id,
            operation="fetch_captions_auto_language",
            max_retries=retries,
            retry_delay=delay
        )

    def list_available_languages_with_retry(
        self,
        video_id: str,
        max_retries: Optional[int] = None,
        retry_delay: Optional[float] = None
    ) -> List[AvailableLanguage]:
        """List available languages with retry logic (US-008).

        Args:
            video_id: YouTube video ID (11 characters).
            max_retries: Override max retry attempts (default: config or 3).
            retry_delay: Override base delay between retries (default: config or 2.0s).

        Returns:
            List of AvailableLanguage objects.

        Raises:
            CaptionFetchError: If all retries fail.
        """
        retries = max_retries if max_retries is not None else self._max_retries
        delay = retry_delay if retry_delay is not None else self._retry_delay

        return self._with_retry(
            func=lambda: self.list_available_languages(video_id),
            video_id=video_id,
            operation="list_available_languages",
            max_retries=retries,
            retry_delay=delay
        )

    def _with_retry(
        self,
        func,
        video_id: str,
        operation: str,
        max_retries: int,
        retry_delay: float
    ):
        """Execute a function with exponential backoff retry logic (US-008).

        Implements retry logic that distinguishes between:
        - CaptionUnavailableError: Permanent, NOT retried (video has no captions)
        - CaptionFetchError: Temporary, IS retried (network issues)

        Backoff formula: delay * (2 ^ attempt)
        Example with delay=2.0: 2s, 4s, 8s, 16s...

        Args:
            func: Callable to execute (no arguments).
            video_id: Video ID for logging context.
            operation: Operation name for logging (e.g., "fetch_captions").
            max_retries: Maximum retry attempts (0 = no retries, just one attempt).
            retry_delay: Base delay for exponential backoff (seconds).

        Returns:
            Result from func.

        Raises:
            CaptionUnavailableError: If captions don't exist (NOT retried).
            CaptionFetchError: If all retries exhausted on temporary errors.
        """
        last_error = None
        total_attempts = max_retries + 1  # +1 for initial attempt

        for attempt in range(total_attempts):
            try:
                result = func()
                if attempt > 0:
                    logger.info(
                        f"Caption {operation} succeeded on attempt {attempt + 1} "
                        f"for video {video_id}"
                    )
                return result

            except CaptionUnavailableError:
                # Permanent error - video has no captions, don't retry
                logger.debug(
                    f"Caption {operation} failed for video {video_id}: "
                    f"no captions available (not retrying)"
                )
                raise

            except CaptionFetchError as e:
                # Temporary error - network issue, retry with backoff
                last_error = e
                is_last_attempt = attempt >= max_retries

                if is_last_attempt:
                    logger.error(
                        f"Caption {operation} failed for video {video_id} "
                        f"after {total_attempts} attempts: {e.reason}"
                    )
                else:
                    wait_time = retry_delay * (2 ** attempt)
                    logger.warning(
                        f"Caption {operation} failed for video {video_id} "
                        f"(attempt {attempt + 1}/{total_attempts}, "
                        f"error_type=CaptionFetchError, reason={e.reason}). "
                        f"Retrying in {wait_time:.1f}s..."
                    )
                    time.sleep(wait_time)

            except Exception as e:
                # Unexpected error - wrap in CaptionFetchError and retry
                last_error = CaptionFetchError(video_id, str(e))
                is_last_attempt = attempt >= max_retries

                if is_last_attempt:
                    logger.error(
                        f"Caption {operation} failed for video {video_id} "
                        f"after {total_attempts} attempts: {e}"
                    )
                else:
                    wait_time = retry_delay * (2 ** attempt)
                    logger.warning(
                        f"Caption {operation} failed for video {video_id} "
                        f"(attempt {attempt + 1}/{total_attempts}, "
                        f"error_type={type(e).__name__}, reason={e}). "
                        f"Retrying in {wait_time:.1f}s..."
                    )
                    time.sleep(wait_time)

        # All retries exhausted
        raise last_error

    def fetch_captions(
        self,
        video_id: str,
        language: str = "en",
        prefer_manual: bool = True
    ) -> CaptionResult:
        """Fetch captions for a YouTube video.

        Args:
            video_id: YouTube video ID (11 characters).
            language: Preferred language code (ISO 639-1).
            prefer_manual: If True, prefer manually uploaded captions over auto-generated.

        Returns:
            CaptionResult with parsed segments and metadata.

        Raises:
            CaptionUnavailableError: If no captions exist for the video.
            CaptionFetchError: If fetch fails due to network/temporary error.
        """
        # Validate video ID format
        if not self._is_valid_video_id(video_id):
            raise CaptionFetchError(video_id, f"Invalid video ID format: {video_id}")

        video_url = f"https://www.youtube.com/watch?v={video_id}"

        # Create temp directory for subtitle files
        with tempfile.TemporaryDirectory() as temp_dir:
            temp_path = Path(temp_dir)

            # Determine which subtitle to fetch
            # Try manual captions first if preferred, then auto-generated
            formats_to_try = []
            if prefer_manual:
                formats_to_try.append((language, False))  # Manual
                formats_to_try.append((language, True))   # Auto
            else:
                formats_to_try.append((language, True))   # Auto
                formats_to_try.append((language, False))  # Manual

            # Also try English as fallback if not already preferred
            if language != "en":
                formats_to_try.append(("en", False))
                formats_to_try.append(("en", True))

            result = None
            last_error = None

            for lang, auto in formats_to_try:
                try:
                    result = self._fetch_subtitle(
                        video_url, video_id, temp_path, lang, auto
                    )
                    if result and result.segments:
                        return result
                except CaptionUnavailableError:
                    continue  # Try next format
                except CaptionFetchError as e:
                    last_error = e
                    continue

            # No captions found in any format
            if last_error:
                raise last_error
            raise CaptionUnavailableError(
                video_id,
                f"No captions available in {language} or en"
            )

    def _fetch_subtitle(
        self,
        video_url: str,
        video_id: str,
        temp_dir: Path,
        language: str,
        auto_generated: bool
    ) -> Optional[CaptionResult]:
        """Fetch a specific subtitle track.

        Args:
            video_url: Full YouTube URL.
            video_id: Video ID for result metadata.
            temp_dir: Temporary directory for downloaded files.
            language: Language code.
            auto_generated: Whether to fetch auto-generated captions.

        Returns:
            CaptionResult if successful, None if no captions for this format.
        """
        # Build yt-dlp command
        sub_flag = '--write-auto-subs' if auto_generated else '--write-subs'
        output_template = str(temp_dir / '%(id)s.%(ext)s')

        cmd = [
            'yt-dlp',
            video_url,
            '--skip-download',  # Don't download video
            sub_flag,
            '--sub-lang', language,
            '--sub-format', 'json3/srv3/vtt/srt/best',  # Prefer structured formats
            '--convert-subs', 'vtt',  # Convert to VTT for parsing
            '-o', output_template,
            '--no-playlist',
            '--no-warnings',
        ]

        # Add cookies if configured
        cmd.extend(self._get_cookies_args())

        try:
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=self._timeout
            )

            # Check for errors indicating no captions
            if result.returncode != 0:
                stderr_lower = result.stderr.lower()
                if any(phrase in stderr_lower for phrase in [
                    'no subtitles',
                    'no automatic captions',
                    'subtitles are disabled',
                    'video unavailable',
                    'private video',
                ]):
                    raise CaptionUnavailableError(video_id, result.stderr[:200])
                else:
                    raise CaptionFetchError(video_id, result.stderr[:200])

            # Find downloaded subtitle file
            sub_files = list(temp_dir.glob(f"{video_id}*.vtt"))
            if not sub_files:
                # Try other extensions
                sub_files = list(temp_dir.glob(f"{video_id}*"))
                sub_files = [f for f in sub_files if f.suffix in ['.vtt', '.srt', '.json3', '.srv3']]

            if not sub_files:
                return None  # No subtitle file created

            sub_file = sub_files[0]
            logger.debug(f"Found subtitle file: {sub_file}")

            # Parse the subtitle file
            segments = self._parse_subtitle_file(sub_file, video_id)

            if not segments:
                return None

            # Determine format from filename
            format_source = sub_file.suffix.lstrip('.')

            return CaptionResult(
                video_id=video_id,
                segments=segments,
                language=language,
                is_auto_generated=auto_generated,
                format_source=format_source
            )

        except subprocess.TimeoutExpired:
            raise CaptionFetchError(video_id, f"Timeout after {self._timeout}s")
        except (CaptionUnavailableError, CaptionFetchError):
            raise
        except Exception as e:
            raise CaptionFetchError(video_id, str(e))

    def _parse_subtitle_file(
        self,
        file_path: Path,
        video_id: str
    ) -> List[CaptionSegment]:
        """Parse a subtitle file into segments.

        Supports VTT, SRT, and JSON3/SRV3 formats.

        Args:
            file_path: Path to subtitle file.
            video_id: Video ID for segment source_file field.

        Returns:
            List of CaptionSegment objects.
        """
        suffix = file_path.suffix.lower()

        try:
            content = file_path.read_text(encoding='utf-8')
        except UnicodeDecodeError:
            content = file_path.read_text(encoding='utf-8', errors='replace')

        if suffix == '.vtt':
            return self._parse_vtt(content, video_id)
        elif suffix == '.srt':
            return self._parse_srt(content, video_id)
        elif suffix in ['.json3', '.srv3', '.json']:
            return self._parse_json3(content, video_id)
        else:
            logger.warning(f"Unknown subtitle format: {suffix}, trying VTT parser")
            return self._parse_vtt(content, video_id)

    def _parse_vtt(self, content: str, video_id: str) -> List[CaptionSegment]:
        """Parse VTT (WebVTT) format captions.

        VTT format:
            WEBVTT

            00:00:01.000 --> 00:00:04.000
            Hello, world!

            00:00:05.000 --> 00:00:08.000
            This is a test.
        """
        segments = []
        lines = content.split('\n')

        # Skip header
        i = 0
        while i < len(lines) and not '-->' in lines[i]:
            i += 1

        # VTT timestamp pattern: HH:MM:SS.mmm or MM:SS.mmm
        timestamp_pattern = re.compile(
            r'(\d{1,2}:)?(\d{2}):(\d{2})[.,](\d{3})\s*-->\s*(\d{1,2}:)?(\d{2}):(\d{2})[.,](\d{3})'
        )

        current_index = 0
        while i < len(lines):
            line = lines[i].strip()

            match = timestamp_pattern.search(line)
            if match:
                # Parse timestamps
                start_time = self._parse_timestamp(match.group(0).split('-->')[0].strip())
                end_time = self._parse_timestamp(match.group(0).split('-->')[1].strip())

                # Collect text lines until empty line or next timestamp
                i += 1
                text_lines = []
                while i < len(lines):
                    text_line = lines[i].strip()
                    if not text_line:
                        i += 1
                        break
                    if timestamp_pattern.search(text_line):
                        break
                    # Skip VTT style tags
                    text_line = re.sub(r'<[^>]+>', '', text_line)
                    if text_line:
                        text_lines.append(text_line)
                    i += 1

                text = ' '.join(text_lines).strip()
                if text:
                    segments.append(CaptionSegment(
                        index=current_index,
                        start_time=start_time,
                        end_time=end_time,
                        text=text,
                        source_file=video_id
                    ))
                    current_index += 1
            else:
                i += 1

        return segments

    def _parse_srt(self, content: str, video_id: str) -> List[CaptionSegment]:
        """Parse SRT (SubRip) format captions.

        SRT format:
            1
            00:00:01,000 --> 00:00:04,000
            Hello, world!

            2
            00:00:05,000 --> 00:00:08,000
            This is a test.
        """
        segments = []
        blocks = re.split(r'\n\s*\n', content.strip())

        for block in blocks:
            lines = block.strip().split('\n')
            if len(lines) < 2:
                continue

            # Find timestamp line
            timestamp_line = None
            text_start_idx = 0
            for idx, line in enumerate(lines):
                if '-->' in line:
                    timestamp_line = line
                    text_start_idx = idx + 1
                    break

            if not timestamp_line:
                continue

            # Parse timestamps
            parts = timestamp_line.split('-->')
            if len(parts) != 2:
                continue

            start_time = self._parse_timestamp(parts[0].strip())
            end_time = self._parse_timestamp(parts[1].strip())

            # Get text
            text = ' '.join(lines[text_start_idx:]).strip()
            text = re.sub(r'<[^>]+>', '', text)  # Remove tags

            if text and start_time is not None and end_time is not None:
                segments.append(CaptionSegment(
                    index=len(segments),
                    start_time=start_time,
                    end_time=end_time,
                    text=text,
                    source_file=video_id
                ))

        return segments

    def _parse_json3(self, content: str, video_id: str) -> List[CaptionSegment]:
        """Parse JSON3/SRV3 format captions from YouTube.

        JSON3 format has 'events' array with 'segs' containing text segments.
        """
        try:
            data = json.loads(content)
        except json.JSONDecodeError:
            logger.warning("Failed to parse JSON3 caption format")
            return []

        segments = []
        events = data.get('events', [])

        for event in events:
            if 'segs' not in event:
                continue

            start_ms = event.get('tStartMs', 0)
            duration_ms = event.get('dDurationMs', 0)

            # Combine all segs text
            text_parts = []
            for seg in event['segs']:
                if 'utf8' in seg:
                    text_parts.append(seg['utf8'])

            text = ''.join(text_parts).strip()
            text = text.replace('\n', ' ')

            if text:
                segments.append(CaptionSegment(
                    index=len(segments),
                    start_time=start_ms / 1000.0,
                    end_time=(start_ms + duration_ms) / 1000.0,
                    text=text,
                    source_file=video_id
                ))

        return segments

    def _parse_timestamp(self, ts: str) -> Optional[float]:
        """Parse a timestamp string to seconds.

        Supports formats:
            HH:MM:SS,mmm (SRT)
            HH:MM:SS.mmm (VTT)
            MM:SS.mmm (VTT short)
        """
        ts = ts.strip()

        # Replace comma with period for SRT format
        ts = ts.replace(',', '.')

        # Pattern for HH:MM:SS.mmm or MM:SS.mmm
        match = re.match(r'^(?:(\d+):)?(\d+):(\d+)\.(\d+)$', ts)
        if match:
            hours = int(match.group(1)) if match.group(1) else 0
            minutes = int(match.group(2))
            seconds = int(match.group(3))
            millis = int(match.group(4).ljust(3, '0')[:3])  # Ensure 3 digits

            return hours * 3600 + minutes * 60 + seconds + millis / 1000.0

        # Try simpler pattern without milliseconds
        match = re.match(r'^(?:(\d+):)?(\d+):(\d+)$', ts)
        if match:
            hours = int(match.group(1)) if match.group(1) else 0
            minutes = int(match.group(2))
            seconds = int(match.group(3))
            return hours * 3600 + minutes * 60 + seconds

        logger.warning(f"Could not parse timestamp: {ts}")
        return None

    def _get_cookies_args(self) -> List[str]:
        """Get yt-dlp cookie arguments from config."""
        if not self.config:
            return []

        try:
            download_config = self.config.download

            # Prefer browser cookies
            cookies_browser = getattr(download_config, 'cookies_from_browser', '')
            if cookies_browser:
                return ['--cookies-from-browser', cookies_browser]

            # Fall back to cookies file
            cookies_path = getattr(download_config, 'cookies_path', '')
            if cookies_path and Path(cookies_path).exists():
                return ['--cookies', cookies_path]
        except AttributeError:
            pass

        return []

    def _is_valid_video_id(self, video_id: str) -> bool:
        """Validate YouTube video ID format.

        YouTube IDs are 11 characters: [A-Za-z0-9_-]
        """
        if not video_id or len(video_id) != 11:
            return False
        return bool(re.match(r'^[A-Za-z0-9_-]{11}$', video_id))


@dataclass
class CachedCaption:
    """Cached caption data for cross-project reuse.

    Stores the full caption result along with fetch metadata.
    """
    video_id: str
    language: str
    segments: List[Dict[str, Any]]  # CaptionSegment.to_dict() format
    is_auto_generated: bool
    format_source: str
    fetch_timestamp: float  # Unix timestamp when fetched
    duration: float = 0.0  # Total caption duration

    def to_dict(self) -> dict:
        """Convert to dictionary for serialization."""
        return {
            'video_id': self.video_id,
            'language': self.language,
            'segments': self.segments,
            'is_auto_generated': self.is_auto_generated,
            'format_source': self.format_source,
            'fetch_timestamp': self.fetch_timestamp,
            'duration': self.duration,
        }

    @classmethod
    def from_dict(cls, data: dict) -> 'CachedCaption':
        """Create from dictionary."""
        return cls(**{k: v for k, v in data.items() if k in cls.__dataclass_fields__})

    def to_caption_result(self) -> CaptionResult:
        """Convert cached data back to CaptionResult."""
        segments = [
            CaptionSegment(
                index=seg.get('index', i),
                start_time=seg.get('start', seg.get('start_time', 0.0)),
                end_time=seg.get('end', seg.get('end_time', 0.0)),
                text=seg.get('text', ''),
                source_file=seg.get('source_file', self.video_id),
            )
            for i, seg in enumerate(self.segments)
        ]
        return CaptionResult(
            video_id=self.video_id,
            segments=segments,
            language=self.language,
            is_auto_generated=self.is_auto_generated,
            format_source=self.format_source,
        )


class CaptionCache(BaseCache):
    """Cache for YouTube captions, enabling cross-project reuse.

    Caches fetched captions by video_id + language code to avoid
    re-fetching the same captions across different projects.

    Features:
    - JSON index for fast lookups
    - Age-based expiration (configurable days)
    - Cache key: video_id_language (e.g., 'dQw4w9WgXcQ_en')
    - Stores caption text, timing info, is_auto_generated, fetch_timestamp

    Usage:
        cache = CaptionCache(config.download.caption_first)

        # Check cache before fetching
        cached = cache.get_caption("dQw4w9WgXcQ", "en")
        if cached:
            result = cached.to_caption_result()
        else:
            result = fetcher.fetch_captions("dQw4w9WgXcQ")
            cache.store(result)

    Example with CaptionFetcher:
        fetcher = CaptionFetcher(config)
        cache = CaptionCache(config.download.caption_first)

        def fetch_with_cache(video_id: str, language: str = "en"):
            cached = cache.get_caption(video_id, language)
            if cached:
                return cached.to_caption_result()
            result = fetcher.fetch_captions(video_id, language=language)
            cache.store(result)
            return result
    """

    def __init__(self, config: Optional['CaptionFirstConfig'] = None):
        """Initialize the caption cache.

        Args:
            config: CaptionFirstConfig with cache settings. If None, uses defaults.
        """
        # Get config values with defaults
        if config:
            cache_dir = getattr(config, 'cache_dir', '~/.matcher_caption_cache')
            max_age_days = getattr(config, 'max_cache_age_days', 30)
            self.enabled = getattr(config, 'cache_captions', True)
        else:
            cache_dir = '~/.matcher_caption_cache'
            max_age_days = 30
            self.enabled = True

        # Expand ~ in cache_dir
        cache_dir = Path(os.path.expanduser(cache_dir))

        # Convert max_age_days to TTL seconds (0 = no expiration)
        ttl_seconds = max_age_days * 24 * 3600 if max_age_days > 0 else 0

        # Initialize BaseCache
        super().__init__(
            cache_dir=cache_dir,
            index_name="caption_cache_index.json",
            ttl_seconds=ttl_seconds,
            auto_save=True
        )

        self.max_age_days = max_age_days

        logger.debug(f"CaptionCache initialized: dir={cache_dir}, "
                    f"ttl={max_age_days} days, enabled={self.enabled}")

    def _make_cache_key(self, video_id: str, language: str) -> str:
        """Create cache key from video_id and language.

        Args:
            video_id: YouTube video ID (11 characters).
            language: ISO 639-1 language code (e.g., 'en').

        Returns:
            Cache key in format 'video_id_language' (e.g., 'dQw4w9WgXcQ_en').
        """
        return f"{video_id}_{language}"

    def _serialize_entry(self, entry: CacheEntry) -> Dict[str, Any]:
        """Serialize CachedCaption to dict."""
        return {
            'data': entry.data,  # CachedCaption.to_dict()
            'cached_at': entry.cached_at,
            'metadata': entry.metadata
        }

    def _deserialize_entry(self, data: Dict[str, Any]) -> CacheEntry:
        """Deserialize dict to CachedCaption entry."""
        return CacheEntry(
            data=data.get('data', {}),
            cached_at=data.get('cached_at', 0.0),
            key='',
            metadata=data.get('metadata', {})
        )

    def get_caption(self, video_id: str, language: str) -> Optional[CachedCaption]:
        """Get cached caption for a video and language.

        Args:
            video_id: YouTube video ID.
            language: ISO 639-1 language code.

        Returns:
            CachedCaption if found and valid, None otherwise.
        """
        if not self.enabled:
            return None

        key = self._make_cache_key(video_id, language)
        entry = self.get(key)

        if entry is None:
            logger.debug(f"Caption cache miss: {key}")
            return None

        try:
            cached = CachedCaption.from_dict(entry.data)
            logger.debug(f"Caption cache hit: {key} "
                        f"({len(cached.segments)} segments, "
                        f"auto={cached.is_auto_generated})")
            return cached
        except Exception as e:
            logger.warning(f"Failed to deserialize cached caption {key}: {e}")
            self.delete(key)
            return None

    def store(self, result: CaptionResult) -> bool:
        """Store a CaptionResult in the cache.

        Args:
            result: CaptionResult to cache.

        Returns:
            True if stored successfully, False otherwise.
        """
        if not self.enabled:
            return False

        if not result.segments:
            logger.debug(f"Not caching empty caption result for {result.video_id}")
            return False

        key = self._make_cache_key(result.video_id, result.language)

        cached = CachedCaption(
            video_id=result.video_id,
            language=result.language,
            segments=[seg.to_dict() for seg in result.segments],
            is_auto_generated=result.is_auto_generated,
            format_source=result.format_source,
            fetch_timestamp=time.time(),
            duration=result.duration,
        )

        self.set(key, cached.to_dict())

        logger.info(f"Cached captions: {key} "
                   f"({len(result.segments)} segments, "
                   f"duration={result.duration:.1f}s, "
                   f"auto={result.is_auto_generated})")
        return True

    def get_or_fetch(
        self,
        fetcher: 'CaptionFetcher',
        video_id: str,
        language: str = "en",
        prefer_manual: bool = True
    ) -> CaptionResult:
        """Get from cache or fetch and cache.

        Convenience method that combines cache lookup and fetching.

        Args:
            fetcher: CaptionFetcher instance to use for fetching.
            video_id: YouTube video ID.
            language: Preferred language code.
            prefer_manual: Prefer manual captions over auto-generated.

        Returns:
            CaptionResult from cache or freshly fetched.

        Raises:
            CaptionUnavailableError: If no captions exist.
            CaptionFetchError: If fetch fails due to network/temporary error.
        """
        # Check cache first
        cached = self.get_caption(video_id, language)
        if cached:
            return cached.to_caption_result()

        # Fetch and cache
        result = fetcher.fetch_captions(video_id, language=language, prefer_manual=prefer_manual)
        self.store(result)
        return result

    def get_or_fetch_with_retry(
        self,
        fetcher: 'CaptionFetcher',
        video_id: str,
        language: str = "en",
        prefer_manual: bool = True,
        max_retries: Optional[int] = None,
        retry_delay: Optional[float] = None
    ) -> CaptionResult:
        """Get from cache or fetch with retry logic and cache (US-008).

        Combines cache lookup with fetch retry logic. Uses exponential backoff
        for network errors (CaptionFetchError) but NOT for permanent errors
        (CaptionUnavailableError).

        Args:
            fetcher: CaptionFetcher instance to use for fetching.
            video_id: YouTube video ID.
            language: Preferred language code.
            prefer_manual: Prefer manual captions over auto-generated.
            max_retries: Override max retry attempts (default: fetcher config).
            retry_delay: Override base delay between retries (default: fetcher config).

        Returns:
            CaptionResult from cache or freshly fetched.

        Raises:
            CaptionUnavailableError: If no captions exist (NOT retried).
            CaptionFetchError: If all retries fail due to network/temporary errors.

        Example:
            cache = CaptionCache(config.download.caption_first)
            fetcher = CaptionFetcher(config)
            try:
                result = cache.get_or_fetch_with_retry(fetcher, "dQw4w9WgXcQ")
            except CaptionFetchError:
                # Mark for transcription fallback
                needs_transcription.append("dQw4w9WgXcQ")
        """
        # Check cache first
        cached = self.get_caption(video_id, language)
        if cached:
            return cached.to_caption_result()

        # Fetch with retry and cache
        result = fetcher.fetch_captions_with_retry(
            video_id,
            language=language,
            prefer_manual=prefer_manual,
            max_retries=max_retries,
            retry_delay=retry_delay
        )
        self.store(result)
        return result

    def invalidate(self, video_id: str, language: Optional[str] = None) -> int:
        """Invalidate cached captions for a video.

        Args:
            video_id: YouTube video ID.
            language: If provided, only invalidate for this language.
                     If None, invalidate all languages for this video.

        Returns:
            Number of cache entries invalidated.
        """
        if language:
            key = self._make_cache_key(video_id, language)
            if self.delete(key):
                logger.debug(f"Invalidated caption cache: {key}")
                return 1
            return 0

        # Invalidate all languages for this video
        invalidated = 0
        for key in list(self.index.keys()):
            if key.startswith(f"{video_id}_"):
                self.delete(key)
                invalidated += 1

        if invalidated:
            logger.debug(f"Invalidated {invalidated} caption cache entries for {video_id}")

        return invalidated

    def get_stats(self) -> Dict[str, Any]:
        """Get cache statistics.

        Returns:
            Dict with cache metrics.
        """
        base_stats = super().get_stats()

        # Add caption-specific stats
        total_segments = 0
        auto_generated_count = 0
        manual_count = 0

        for entry in self.get_all().values():
            try:
                cached = CachedCaption.from_dict(entry.data)
                total_segments += len(cached.segments)
                if cached.is_auto_generated:
                    auto_generated_count += 1
                else:
                    manual_count += 1
            except Exception:
                pass

        base_stats.update({
            'total_segments': total_segments,
            'auto_generated_entries': auto_generated_count,
            'manual_entries': manual_count,
            'max_age_days': self.max_age_days,
            'enabled': self.enabled,
        })

        return base_stats


class CaptionNormalizationError(CaptionError):
    """Raised when caption normalization fails."""

    def __init__(self, reason: str = ""):
        self.reason = reason
        message = "Caption normalization failed"
        if reason:
            message += f": {reason}"
        super().__init__(message)


@dataclass
class NormalizationConfig:
    """Configuration for caption timestamp normalization.

    Attributes:
        overlap_strategy: How to handle overlapping segments.
            - 'merge': Merge overlapping segments into one.
            - 'split': Split at the midpoint of overlap.
            - 'truncate': Truncate earlier segment's end to later's start.
        gap_strategy: How to handle gaps between segments.
            - 'extend': Extend previous segment's end to next segment's start.
            - 'placeholder': Insert empty placeholder segments.
            - 'ignore': Leave gaps as-is.
        max_gap_to_extend: Maximum gap size (seconds) to extend (larger gaps use placeholder).
        min_segment_duration: Minimum valid segment duration (seconds).
        validate_timestamps: Whether to validate and fix timestamps.
    """

    overlap_strategy: str = "truncate"
    gap_strategy: str = "ignore"
    max_gap_to_extend: float = 1.0
    min_segment_duration: float = 0.1
    validate_timestamps: bool = True


class CaptionNormalizer:
    """Normalizes YouTube caption timestamps for consistency.

    YouTube captions can have irregular timing:
    - Overlapping segments (two segments with overlapping time ranges)
    - Gaps between segments
    - Inconsistent timestamp formats (VTT, SRT, JSON3)
    - Invalid timestamps (negative, end < start)

    This class normalizes segments to a consistent format expected by
    the matching stage.

    Usage:
        normalizer = CaptionNormalizer()
        normalized = normalizer.normalize(caption_result.segments, video_id="abc123")

        # With custom config:
        config = NormalizationConfig(overlap_strategy="merge", gap_strategy="extend")
        normalizer = CaptionNormalizer(config)
        normalized = normalizer.normalize(segments)

    Example:
        >>> segments = [
        ...     CaptionSegment(0, 0.0, 5.0, "First", "vid"),
        ...     CaptionSegment(1, 4.0, 8.0, "Second", "vid"),  # Overlaps with first
        ...     CaptionSegment(2, 10.0, 12.0, "Third", "vid"),  # Gap before this
        ... ]
        >>> normalizer = CaptionNormalizer()
        >>> normalized = normalizer.normalize(segments)
    """

    def __init__(self, config: Optional[NormalizationConfig] = None):
        """Initialize the normalizer.

        Args:
            config: Optional normalization configuration.
        """
        self.config = config or NormalizationConfig()

    def normalize(
        self,
        segments: List[CaptionSegment],
        video_id: str = ""
    ) -> List[CaptionSegment]:
        """Normalize a list of caption segments.

        Applies the following normalization steps:
        1. Validate and fix individual segment timestamps
        2. Sort segments by start time
        3. Handle overlapping segments (based on overlap_strategy)
        4. Handle gaps between segments (based on gap_strategy)
        5. Re-index segments sequentially

        Args:
            segments: List of CaptionSegment to normalize.
            video_id: Video ID for source_file field in new segments.

        Returns:
            List of normalized CaptionSegment objects.

        Raises:
            CaptionNormalizationError: If normalization fails catastrophically.
        """
        if not segments:
            return []

        logger.debug(f"Normalizing {len(segments)} caption segments for video {video_id}")

        # Step 1: Validate and fix individual timestamps
        if self.config.validate_timestamps:
            segments = [self._validate_segment(seg, video_id) for seg in segments]
            # Filter out None (invalid segments)
            segments = [seg for seg in segments if seg is not None]

        if not segments:
            logger.warning("All segments were invalid after validation")
            return []

        # Step 2: Sort by start time
        segments = sorted(segments, key=lambda s: s.start_time)

        # Step 3: Handle overlapping segments
        segments = self._handle_overlaps(segments, video_id)

        # Step 4: Handle gaps
        segments = self._handle_gaps(segments, video_id)

        # Step 5: Re-index
        segments = self._reindex(segments)

        logger.debug(f"Normalization complete: {len(segments)} segments")
        return segments

    def _validate_segment(
        self,
        segment: CaptionSegment,
        video_id: str
    ) -> Optional[CaptionSegment]:
        """Validate and fix a single segment's timestamps.

        Validation rules:
        - start_time must be >= 0
        - end_time must be > start_time
        - Duration must be >= min_segment_duration

        Args:
            segment: Segment to validate.
            video_id: Video ID for logging.

        Returns:
            Fixed segment, or None if segment is invalid and unfixable.
        """
        start = segment.start_time
        end = segment.end_time

        # Fix negative start time
        if start < 0:
            logger.debug(f"Fixing negative start_time ({start}) in segment {segment.index}")
            start = 0.0

        # Fix negative end time
        if end < 0:
            logger.debug(f"Invalid negative end_time ({end}) in segment {segment.index}")
            return None

        # Fix end <= start
        if end <= start:
            # Try extending end by minimum duration
            new_end = start + self.config.min_segment_duration
            logger.debug(
                f"Fixing end <= start ({end} <= {start}) in segment {segment.index}, "
                f"extending to {new_end}"
            )
            end = new_end

        # Check minimum duration
        duration = end - start
        if duration < self.config.min_segment_duration:
            logger.debug(
                f"Segment {segment.index} duration ({duration}) below minimum "
                f"({self.config.min_segment_duration}), extending"
            )
            end = start + self.config.min_segment_duration

        # Skip empty text
        if not segment.text.strip():
            logger.debug(f"Skipping empty segment {segment.index}")
            return None

        return CaptionSegment(
            index=segment.index,
            start_time=start,
            end_time=end,
            text=segment.text,
            source_file=segment.source_file or video_id
        )

    def _handle_overlaps(
        self,
        segments: List[CaptionSegment],
        video_id: str
    ) -> List[CaptionSegment]:
        """Handle overlapping segments based on strategy.

        Args:
            segments: Sorted list of segments.
            video_id: Video ID for new segments.

        Returns:
            List of segments with overlaps resolved.
        """
        if len(segments) < 2:
            return segments

        strategy = self.config.overlap_strategy
        result = []

        i = 0
        while i < len(segments):
            current = segments[i]

            # Check for overlap with next segment
            if i + 1 < len(segments):
                next_seg = segments[i + 1]

                if current.end_time > next_seg.start_time:
                    # Overlap detected
                    logger.debug(
                        f"Overlap detected: segment {current.index} "
                        f"({current.start_time:.2f}-{current.end_time:.2f}) overlaps with "
                        f"segment {next_seg.index} ({next_seg.start_time:.2f}-{next_seg.end_time:.2f})"
                    )

                    if strategy == "merge":
                        # Merge overlapping segments
                        merged = self._merge_segments(current, next_seg, video_id)
                        # Replace next segment with merged for further processing
                        segments[i + 1] = merged
                        i += 1
                        continue

                    elif strategy == "split":
                        # Split at midpoint
                        midpoint = (current.end_time + next_seg.start_time) / 2
                        current = CaptionSegment(
                            index=current.index,
                            start_time=current.start_time,
                            end_time=midpoint,
                            text=current.text,
                            source_file=current.source_file or video_id
                        )
                        segments[i + 1] = CaptionSegment(
                            index=next_seg.index,
                            start_time=midpoint,
                            end_time=next_seg.end_time,
                            text=next_seg.text,
                            source_file=next_seg.source_file or video_id
                        )

                    elif strategy == "truncate":
                        # Truncate current's end to next's start
                        current = CaptionSegment(
                            index=current.index,
                            start_time=current.start_time,
                            end_time=next_seg.start_time,
                            text=current.text,
                            source_file=current.source_file or video_id
                        )

            result.append(current)
            i += 1

        return result

    def _merge_segments(
        self,
        seg1: CaptionSegment,
        seg2: CaptionSegment,
        video_id: str
    ) -> CaptionSegment:
        """Merge two overlapping segments into one.

        Args:
            seg1: First segment (earlier start time).
            seg2: Second segment (overlapping).
            video_id: Video ID for merged segment.

        Returns:
            Merged CaptionSegment.
        """
        return CaptionSegment(
            index=seg1.index,
            start_time=min(seg1.start_time, seg2.start_time),
            end_time=max(seg1.end_time, seg2.end_time),
            text=f"{seg1.text} {seg2.text}".strip(),
            source_file=seg1.source_file or seg2.source_file or video_id
        )

    def _handle_gaps(
        self,
        segments: List[CaptionSegment],
        video_id: str
    ) -> List[CaptionSegment]:
        """Handle gaps between segments based on strategy.

        Args:
            segments: List of segments with overlaps resolved.
            video_id: Video ID for new segments.

        Returns:
            List of segments with gaps handled.
        """
        if len(segments) < 2 or self.config.gap_strategy == "ignore":
            return segments

        strategy = self.config.gap_strategy
        result = []

        for i, segment in enumerate(segments):
            result.append(segment)

            # Check for gap before next segment
            if i + 1 < len(segments):
                next_seg = segments[i + 1]
                gap = next_seg.start_time - segment.end_time

                if gap > 0:
                    logger.debug(
                        f"Gap detected: {gap:.2f}s between segment {segment.index} "
                        f"and {next_seg.index}"
                    )

                    if strategy == "extend":
                        # Extend if gap is small enough
                        if gap <= self.config.max_gap_to_extend:
                            # Extend current segment's end
                            result[-1] = CaptionSegment(
                                index=segment.index,
                                start_time=segment.start_time,
                                end_time=next_seg.start_time,
                                text=segment.text,
                                source_file=segment.source_file or video_id
                            )
                        else:
                            # Insert placeholder for large gaps
                            placeholder = CaptionSegment(
                                index=-1,  # Will be re-indexed
                                start_time=segment.end_time,
                                end_time=next_seg.start_time,
                                text="",  # Empty placeholder
                                source_file=video_id
                            )
                            result.append(placeholder)

                    elif strategy == "placeholder":
                        # Always insert placeholder
                        placeholder = CaptionSegment(
                            index=-1,
                            start_time=segment.end_time,
                            end_time=next_seg.start_time,
                            text="",
                            source_file=video_id
                        )
                        result.append(placeholder)

        return result

    def _reindex(self, segments: List[CaptionSegment]) -> List[CaptionSegment]:
        """Re-index segments sequentially.

        Args:
            segments: List of segments to re-index.

        Returns:
            List of segments with sequential indexes starting from 0.
        """
        return [
            CaptionSegment(
                index=i,
                start_time=seg.start_time,
                end_time=seg.end_time,
                text=seg.text,
                source_file=seg.source_file
            )
            for i, seg in enumerate(segments)
        ]

    def validate_continuity(
        self,
        segments: List[CaptionSegment]
    ) -> List[str]:
        """Validate segment timing continuity.

        Checks for common issues:
        - Negative durations
        - end_time < start_time
        - Overlaps
        - Gaps

        Args:
            segments: List of segments to validate.

        Returns:
            List of warning messages (empty if all valid).
        """
        warnings = []

        for i, seg in enumerate(segments):
            # Check individual segment
            if seg.end_time < seg.start_time:
                warnings.append(
                    f"Segment {i}: end_time ({seg.end_time}) < start_time ({seg.start_time})"
                )

            duration = seg.end_time - seg.start_time
            if duration <= 0:
                warnings.append(f"Segment {i}: non-positive duration ({duration})")

            # Check relationship with next segment
            if i + 1 < len(segments):
                next_seg = segments[i + 1]

                if seg.end_time > next_seg.start_time:
                    overlap = seg.end_time - next_seg.start_time
                    warnings.append(
                        f"Segments {i}-{i+1}: overlap of {overlap:.2f}s"
                    )

        return warnings

    @staticmethod
    def convert_timestamp_to_seconds(timestamp: str) -> Optional[float]:
        """Convert a timestamp string to seconds.

        Supports formats:
        - HH:MM:SS,mmm (SRT)
        - HH:MM:SS.mmm (VTT)
        - MM:SS.mmm (VTT short)
        - Seconds as float string

        Args:
            timestamp: Timestamp string to convert.

        Returns:
            Time in seconds, or None if parsing fails.
        """
        if not timestamp:
            return None

        timestamp = timestamp.strip().replace(',', '.')

        # Try float directly (e.g., "1.5")
        try:
            return float(timestamp)
        except ValueError:
            pass

        # Pattern for HH:MM:SS.mmm or MM:SS.mmm
        match = re.match(r'^(?:(\d+):)?(\d+):(\d+)(?:\.(\d+))?$', timestamp)
        if match:
            hours = int(match.group(1)) if match.group(1) else 0
            minutes = int(match.group(2))
            seconds = int(match.group(3))
            millis = int(match.group(4).ljust(3, '0')[:3]) if match.group(4) else 0

            return hours * 3600 + minutes * 60 + seconds + millis / 1000.0

        logger.warning(f"Could not parse timestamp: {timestamp}")
        return None

    @staticmethod
    def seconds_to_vtt_timestamp(seconds: float) -> str:
        """Convert seconds to VTT timestamp format.

        Args:
            seconds: Time in seconds.

        Returns:
            VTT timestamp string (HH:MM:SS.mmm).
        """
        if seconds < 0:
            seconds = 0

        hours = int(seconds // 3600)
        minutes = int((seconds % 3600) // 60)
        secs = int(seconds % 60)
        millis = int((seconds * 1000) % 1000)

        return f"{hours:02d}:{minutes:02d}:{secs:02d}.{millis:03d}"

    @staticmethod
    def seconds_to_srt_timestamp(seconds: float) -> str:
        """Convert seconds to SRT timestamp format.

        Args:
            seconds: Time in seconds.

        Returns:
            SRT timestamp string (HH:MM:SS,mmm).
        """
        vtt_ts = CaptionNormalizer.seconds_to_vtt_timestamp(seconds)
        return vtt_ts.replace('.', ',')


@dataclass
class CaptionMetrics:
    """
    Tracks caption fetch statistics for pipeline reporting.

    Implements US-011: Add caption fetch metrics and reporting.

    Tracks:
    - Fetch attempts, successes, failures, cache hits
    - Language distribution
    - Quality distribution (human, auto, unavailable)
    - Total segments fetched

    Usage:
        metrics = CaptionMetrics()
        metrics.record_fetch_attempt("dQw4w9WgXcQ")
        metrics.record_fetch_success("dQw4w9WgXcQ", language="en", quality="high")
        # ... later ...
        print(metrics.summary())

    Attributes:
        fetch_attempts: Total fetch attempts made
        successes: Number of successful caption fetches
        failures: Number of failed caption fetches (unavailable/error)
        cache_hits: Number of cache hits (captions loaded from cache)
        language_distribution: Dict mapping language code -> count
        quality_distribution: Dict mapping quality level -> count
        total_segments: Total caption segments fetched
    """

    # Core counts
    fetch_attempts: int = 0
    successes: int = 0
    failures: int = 0
    cache_hits: int = 0

    # Distribution tracking
    language_distribution: Dict[str, int] = field(default_factory=dict)
    quality_distribution: Dict[str, int] = field(default_factory=dict)

    # Additional metrics
    total_segments: int = 0
    auto_generated_count: int = 0
    human_caption_count: int = 0

    def record_fetch_attempt(self, video_id: str = "") -> None:
        """Record a caption fetch attempt.

        Args:
            video_id: Optional video ID for logging context.
        """
        self.fetch_attempts += 1
        logger.debug(f"Caption fetch attempt recorded for {video_id or 'unknown'}")

    def record_fetch_success(
        self,
        video_id: str = "",
        language: str = "en",
        quality: str = "medium",
        segment_count: int = 0,
        is_auto_generated: bool = False
    ) -> None:
        """Record a successful caption fetch.

        Args:
            video_id: Video ID for logging.
            language: ISO 639-1 language code (e.g., 'en').
            quality: Caption quality level ('high', 'medium', 'low').
            segment_count: Number of caption segments fetched.
            is_auto_generated: Whether captions are auto-generated.
        """
        self.successes += 1
        self.total_segments += segment_count

        # Track language distribution
        self.language_distribution[language] = self.language_distribution.get(language, 0) + 1

        # Track quality distribution
        self.quality_distribution[quality] = self.quality_distribution.get(quality, 0) + 1

        # Track auto vs human
        if is_auto_generated:
            self.auto_generated_count += 1
        else:
            self.human_caption_count += 1

        logger.debug(
            f"Caption fetch success for {video_id or 'unknown'}: "
            f"lang={language}, quality={quality}, segments={segment_count}"
        )

    def record_fetch_failure(
        self,
        video_id: str = "",
        reason: str = "unknown"
    ) -> None:
        """Record a failed caption fetch.

        Args:
            video_id: Video ID for logging.
            reason: Reason for failure (e.g., 'unavailable', 'error', 'timeout').
        """
        self.failures += 1

        # Track as 'unavailable' quality
        self.quality_distribution['unavailable'] = self.quality_distribution.get('unavailable', 0) + 1

        logger.debug(f"Caption fetch failure for {video_id or 'unknown'}: {reason}")

    def record_cache_hit(
        self,
        video_id: str = "",
        language: str = "en",
        quality: str = "medium",
        segment_count: int = 0,
        is_auto_generated: bool = False
    ) -> None:
        """Record a cache hit (captions loaded from cache).

        Args:
            video_id: Video ID for logging.
            language: ISO 639-1 language code.
            quality: Caption quality level.
            segment_count: Number of segments in cached captions.
            is_auto_generated: Whether cached captions are auto-generated.
        """
        self.cache_hits += 1
        self.total_segments += segment_count

        # Track language distribution
        self.language_distribution[language] = self.language_distribution.get(language, 0) + 1

        # Track quality distribution
        self.quality_distribution[quality] = self.quality_distribution.get(quality, 0) + 1

        # Track auto vs human
        if is_auto_generated:
            self.auto_generated_count += 1
        else:
            self.human_caption_count += 1

        logger.debug(f"Caption cache hit for {video_id or 'unknown'}: lang={language}")

    @property
    def total_processed(self) -> int:
        """Total videos processed (successes + failures + cache_hits)."""
        return self.successes + self.failures + self.cache_hits

    @property
    def success_rate(self) -> float:
        """Calculate fetch success rate as percentage.

        Returns:
            Success rate percentage (0-100), or 0.0 if no attempts.
        """
        total = self.successes + self.failures
        if total == 0:
            return 0.0
        return round(100.0 * self.successes / total, 1)

    @property
    def cache_hit_rate(self) -> float:
        """Calculate cache hit rate as percentage.

        Returns:
            Cache hit rate percentage (0-100), or 0.0 if no processed videos.
        """
        total = self.total_processed
        if total == 0:
            return 0.0
        return round(100.0 * self.cache_hits / total, 1)

    def summary(self) -> str:
        """Generate human-readable summary for pipeline report.

        Returns:
            Multi-line string suitable for printing in the report.
        """
        lines = []

        # Basic stats
        lines.append(
            f"Caption fetch: {self.fetch_attempts} attempts, "
            f"{self.successes} succeeded, {self.failures} failed, "
            f"{self.cache_hits} from cache"
        )

        if self.total_processed > 0:
            lines.append(
                f"  Success rate: {self.success_rate}%, "
                f"Cache hit rate: {self.cache_hit_rate}%"
            )
            lines.append(f"  Total segments: {self.total_segments}")

        # Caption source breakdown
        if self.human_caption_count > 0 or self.auto_generated_count > 0:
            lines.append(
                f"  Caption sources: {self.human_caption_count} human, "
                f"{self.auto_generated_count} auto, "
                f"{self.quality_distribution.get('unavailable', 0)} unavailable"
            )

        # Language distribution (top 5)
        if self.language_distribution:
            sorted_langs = sorted(
                self.language_distribution.items(),
                key=lambda x: x[1],
                reverse=True
            )[:5]
            lang_str = ", ".join(f"{lang}: {count}" for lang, count in sorted_langs)
            lines.append(f"  Languages: {lang_str}")

        # Quality distribution
        if self.quality_distribution:
            quality_str = ", ".join(
                f"{q}: {c}" for q, c in sorted(self.quality_distribution.items())
            )
            lines.append(f"  Quality: {quality_str}")

        return "\n".join(lines)

    def to_dict(self) -> Dict[str, Any]:
        """Serialize metrics to dictionary for checkpoint/JSON.

        Returns:
            Dict representation of all metrics.
        """
        return {
            'fetch_attempts': self.fetch_attempts,
            'successes': self.successes,
            'failures': self.failures,
            'cache_hits': self.cache_hits,
            'language_distribution': dict(self.language_distribution),
            'quality_distribution': dict(self.quality_distribution),
            'total_segments': self.total_segments,
            'auto_generated_count': self.auto_generated_count,
            'human_caption_count': self.human_caption_count,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'CaptionMetrics':
        """Create CaptionMetrics from dictionary.

        Args:
            data: Dict from to_dict() or checkpoint.

        Returns:
            New CaptionMetrics instance.
        """
        if not data:
            return cls()

        return cls(
            fetch_attempts=data.get('fetch_attempts', 0),
            successes=data.get('successes', 0),
            failures=data.get('failures', 0),
            cache_hits=data.get('cache_hits', 0),
            language_distribution=data.get('language_distribution', {}),
            quality_distribution=data.get('quality_distribution', {}),
            total_segments=data.get('total_segments', 0),
            auto_generated_count=data.get('auto_generated_count', 0),
            human_caption_count=data.get('human_caption_count', 0),
        )

    def merge(self, other: 'CaptionMetrics') -> 'CaptionMetrics':
        """Merge another CaptionMetrics into this one.

        Useful for cross-session aggregation. Modifies self in-place
        and returns self for chaining.

        Args:
            other: Another CaptionMetrics to merge.

        Returns:
            Self after merging.
        """
        self.fetch_attempts += other.fetch_attempts
        self.successes += other.successes
        self.failures += other.failures
        self.cache_hits += other.cache_hits
        self.total_segments += other.total_segments
        self.auto_generated_count += other.auto_generated_count
        self.human_caption_count += other.human_caption_count

        # Merge language distribution
        for lang, count in other.language_distribution.items():
            self.language_distribution[lang] = self.language_distribution.get(lang, 0) + count

        # Merge quality distribution
        for quality, count in other.quality_distribution.items():
            self.quality_distribution[quality] = self.quality_distribution.get(quality, 0) + count

        return self

    def clear(self) -> None:
        """Reset all metrics."""
        self.fetch_attempts = 0
        self.successes = 0
        self.failures = 0
        self.cache_hits = 0
        self.language_distribution = {}
        self.quality_distribution = {}
        self.total_segments = 0
        self.auto_generated_count = 0
        self.human_caption_count = 0
